//+------------------------------------------------------------------+
//|                                                   __EA_NAME__.mq5 |
//|            Generated by the MQL5 EA Factory & Curation Dashboard |
//|  Strategy ID: __STRATEGY_ID__                                     |
//+------------------------------------------------------------------+
#property copyright "EA Factory"
#property link      "https://www.mql5.com"
#property version   "1.00"
#property description "__EA_DESCRIPTION__"

#include <Trade\Trade.mqh>

//--- General inputs
input group "=== General ==="
input long   InpMagic           = __MAGIC__;   // Magic number
input double InpLots            = __LOTS__;    // Fixed lot size
input double InpMaxSpreadPoints = __MAX_SPREAD__; // Max allowed spread (points)
input double InpMaxOpenLots     = __MAX_OPEN_LOTS__; // Max total open lots
input int    InpMaxRetries      = 3;           // Trade retry attempts
input int    InpRetryBaseMs     = 300;         // Retry backoff base (ms)
input bool   InpShowDashboard   = true;        // Show chart dashboard

//--- Trade management: stop loss
input group "=== Trade mgmt: stop loss ==="
input int    Inp_X_sl_mode      = __TM_SL_MODE__;    // SL mode: 0=off 1=fixed 2=ATR
input int    Inp_X_atr_period   = __TM_ATR_PERIOD__; // ATR period (adaptive SL/trail)
input double Inp_X_atr_sl_mult  = __TM_ATR_SL_MULT__;// ATR stop multiplier
//--- Trade management: take profit
input group "=== Trade mgmt: take profit ==="
input int    Inp_X_tp_mode      = __TM_TP_MODE__;    // TP mode: 0=off 1=fixed 2=R:R
input double Inp_X_tp_rr         = __TM_TP_RR__;      // Reward:risk multiple
//--- Trade management: trailing
input group "=== Trade mgmt: trailing ==="
input int    Inp_X_trail_mode           = __TM_TRAIL_MODE__;   // 0=off 1=fixed 2=ATR 3=chandelier
input double Inp_X_trail_start_points    = __TM_TRAIL_START__;  // Arm after +points profit
input double Inp_X_trail_distance_points = __TM_TRAIL_DIST__;   // Fixed trail distance (points)
input double Inp_X_trail_atr_mult        = __TM_TRAIL_ATR_MULT__; // ATR/chandelier multiplier
input int    Inp_X_chandelier_lookback   = __TM_CHAND_LB__;     // Chandelier lookback (bars)
input double Inp_X_trail_step_points      = __TM_TRAIL_STEP__;  // Min favorable move to shift SL
//--- Trade management: breakeven
input group "=== Trade mgmt: breakeven ==="
input int    Inp_X_breakeven         = __TM_BREAKEVEN__;    // 0=off 1=on
input double Inp_X_be_trigger_points  = __TM_BE_TRIGGER__;  // Breakeven trigger (points)
input double Inp_X_be_offset_points   = __TM_BE_OFFSET__;   // Breakeven offset (points)
//--- Trade management: position sizing
input group "=== Trade mgmt: position sizing ==="
input int    Inp_X_lot_mode      = __TM_LOT_MODE__;   // 0=fixed 1=risk%
input double Inp_X_risk_percent   = __TM_RISK_PCT__;  // Risk % of equity per trade
//--- Trade management: filters / safeguards
input group "=== Trade mgmt: filters ==="
input int    Inp_X_time_filter          = __TM_TIME_FILTER__;   // 0=off 1=on
input int    Inp_X_start_hour            = __TM_START_HOUR__;    // Session start hour
input int    Inp_X_end_hour              = __TM_END_HOUR__;      // Session end hour
input int    Inp_X_limit_trades_per_day  = __TM_LIMIT_TRADES__; // 0=off 1=on
input int    Inp_X_max_trades_per_day    = __TM_MAX_TRADES__;   // Max entries per day
input int    Inp_X_daily_loss_enabled    = __TM_DAILY_LOSS__;   // 0=off 1=on
input double Inp_X_daily_loss_pct        = __TM_DAILY_LOSS_PCT__; // Daily loss halt (%)
input int    Inp_X_cooldown_enabled      = __TM_COOLDOWN__;     // 0=off 1=on
input int    Inp_X_cooldown_bars         = __TM_COOLDOWN_BARS__;// Bars to wait after a loss

__INPUT_BLOCKS__

//--- Globals
CTrade   g_trade;
datetime g_last_bar_time = 0;
int      g_bars_seen = 0;
bool     g_any_trade = false;

//--- Trade-management state
int      g_tm_atr_handle       = INVALID_HANDLE;
int      g_tm_day              = -1;
int      g_tm_trades_today     = 0;
double   g_tm_day_start_balance = 0.0;
datetime g_tm_cooldown_until   = 0;
int      g_tm_prev_positions   = 0;
double   g_tm_prev_balance     = 0.0;

__GLOBAL_DECLS__

//+------------------------------------------------------------------+
//| Initialization — must succeed on every symbol the validator uses  |
//+------------------------------------------------------------------+
int OnInit()
  {
   g_trade.SetExpertMagicNumber(InpMagic);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetAsyncMode(false);

   if(Inp_X_sl_mode == 2 || Inp_X_trail_mode == 2 || Inp_X_trail_mode == 3)
      g_tm_atr_handle = iATR(_Symbol, _Period, Inp_X_atr_period);
   g_tm_day_start_balance = AccountInfoDouble(ACCOUNT_BALANCE);
   g_tm_prev_balance = g_tm_day_start_balance;

__INIT_INDICATORS__

   if(InpShowDashboard)
      DashboardCreate();
   return(INIT_SUCCEEDED);
  }

//+------------------------------------------------------------------+
//| Deinitialization: release every indicator handle                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   if(g_tm_atr_handle != INVALID_HANDLE)
      IndicatorRelease(g_tm_atr_handle);
__RELEASE_INDICATORS__
   ObjectsDeleteAll(0, "EAF_");
  }

//+------------------------------------------------------------------+
//| Safe division: never divide by zero                               |
//+------------------------------------------------------------------+
double SafeDiv(const double a, const double b)
  {
   if(MathAbs(b) < 1e-12)
      return(0.0);
   return(a / b);
  }

//+------------------------------------------------------------------+
//| Trading permission (never fail OnInit; skip trading when blocked) |
//+------------------------------------------------------------------+
bool TradingAllowed()
  {
   if(MQLInfoInteger(MQL_TESTER))
      return(true);
   if(!TerminalInfoInteger(TERMINAL_TRADE_ALLOWED))
      return(false);
   if(!MQLInfoInteger(MQL_TRADE_ALLOWED))
      return(false);
   return(true);
  }

//+------------------------------------------------------------------+
//| Account margin mode (netting vs hedging)                            |
//+------------------------------------------------------------------+
bool IsHedgingAccount()
  {
   const long mode = AccountInfoInteger(ACCOUNT_MARGIN_MODE);
   return(mode == ACCOUNT_MARGIN_MODE_RETAIL_HEDGING ||
          mode == ACCOUNT_MARGIN_MODE_EXCHANGE);
  }

//+------------------------------------------------------------------+
//| History must be synchronized before any buffer access             |
//+------------------------------------------------------------------+
bool HistoryReady(const int min_bars)
  {
   if(!SeriesInfoInteger(_Symbol, _Period, SERIES_SYNCHRONIZED))
      return(false);
   if(Bars(_Symbol, _Period) < min_bars)
      return(false);
   return(true);
  }

//+------------------------------------------------------------------+
//| Checked CopyBuffer into a dynamically sized array                 |
//+------------------------------------------------------------------+
bool SafeCopyBuffer(const int handle, const int buffer, const int start,
                    const int count, double &dst[])
  {
   if(handle == INVALID_HANDLE)
      return(false);
   if(BarsCalculated(handle) < count + start)
      return(false);
   ArraySetAsSeries(dst, true);
   if(ArrayResize(dst, count) != count)
      return(false);
   const int copied = CopyBuffer(handle, buffer, start, count, dst);
   return(copied == count);
  }

//+------------------------------------------------------------------+
//| Checked price-series copies                                       |
//+------------------------------------------------------------------+
bool SafeCopyHigh(const int start, const int count, double &dst[])
  {
   ArraySetAsSeries(dst, true);
   if(ArrayResize(dst, count) != count)
      return(false);
   return(CopyHigh(_Symbol, _Period, start, count, dst) == count);
  }

bool SafeCopyLow(const int start, const int count, double &dst[])
  {
   ArraySetAsSeries(dst, true);
   if(ArrayResize(dst, count) != count)
      return(false);
   return(CopyLow(_Symbol, _Period, start, count, dst) == count);
  }

bool SafeCopyClose(const int start, const int count, double &dst[])
  {
   ArraySetAsSeries(dst, true);
   if(ArrayResize(dst, count) != count)
      return(false);
   return(CopyClose(_Symbol, _Period, start, count, dst) == count);
  }

//+------------------------------------------------------------------+
//| Trading environment gates                                         |
//+------------------------------------------------------------------+
bool MarketOpen()
  {
   return(SymbolInfoInteger(_Symbol, SYMBOL_TRADE_MODE) == SYMBOL_TRADE_MODE_FULL);
  }

bool SpreadOK()
  {
   const double spread_points = (double)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   return(spread_points <= InpMaxSpreadPoints);
  }

//+------------------------------------------------------------------+
//| CheckVolumeValue — official Market validation pattern             |
//+------------------------------------------------------------------+
bool CheckVolumeValue(const double volume, string &description)
  {
   const double min_volume  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   const double max_volume  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   const double volume_step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(volume < min_volume)
     {
      description = StringFormat("Volume %.2f < min %.2f", volume, min_volume);
      return(false);
     }
   if(volume > max_volume)
     {
      description = StringFormat("Volume %.2f > max %.2f", volume, max_volume);
      return(false);
     }
   if(volume_step > 0.0)
     {
      const double steps = SafeDiv(volume - min_volume, volume_step);
      const double snapped = min_volume + MathFloor(steps + 0.5) * volume_step;
      if(MathAbs(snapped - volume) > volume_step * 0.01)
        {
         description = StringFormat("Volume %.2f not on step %.2f", volume, volume_step);
         return(false);
        }
     }
   const double limit = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_LIMIT);
   if(limit > 0.0 && TotalOurLots() + volume > limit)
     {
      description = StringFormat("Volume limit %.2f exceeded", limit);
      return(false);
     }
   description = "OK";
   return(true);
  }

//+------------------------------------------------------------------+
//| Normalize a lot request to broker constraints                     |
//+------------------------------------------------------------------+
double NormalizeLots(double lots)
  {
   const double lot_min  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   const double lot_max  = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   const double lot_step = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   if(lot_step > 0.0)
      lots = MathFloor(SafeDiv(lots, lot_step)) * lot_step;
   lots = MathMax(lot_min, MathMin(lot_max, lots));
   return(lots);
  }

//+------------------------------------------------------------------+
//| CheckMoneyForTrade — official Market validation pattern           |
//+------------------------------------------------------------------+
bool CheckMoneyForTrade(const string symb, const double lots,
                        const ENUM_ORDER_TYPE type)
  {
   MqlTick tick;
   if(!SymbolInfoTick(symb, tick))
      return(false);
   const double price = (type == ORDER_TYPE_BUY) ? tick.ask : tick.bid;
   if(price <= 0.0)
      return(false);
   double margin = 0.0;
   if(!OrderCalcMargin(type, symb, lots, price, margin))
      return(false);
   const double free_margin = AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   return(margin <= free_margin);
  }

//+------------------------------------------------------------------+
//| Adjust SL/TP to respect SYMBOL_TRADE_STOPS_LEVEL + spread         |
//+------------------------------------------------------------------+
void AdjustStops(const ENUM_ORDER_TYPE type, double &sl, double &tp)
  {
   const int stops_level = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   const int freeze_level = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_FREEZE_LEVEL);
   const int min_dist = stops_level + freeze_level;
   if(min_dist <= 0)
      return;
   const double dist = min_dist * _Point;
   const double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   const double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   if(type == ORDER_TYPE_BUY)
     {
      if(sl > 0.0 && bid - sl < dist)
         sl = NormalizeDouble(bid - dist, _Digits);
      if(tp > 0.0 && tp - bid < dist)
         tp = NormalizeDouble(bid + dist, _Digits);
     }
   else
     {
      if(sl > 0.0 && sl - ask < dist)
         sl = NormalizeDouble(ask + dist, _Digits);
      if(tp > 0.0 && ask - tp < dist)
         tp = NormalizeDouble(ask - dist, _Digits);
     }
  }

//+------------------------------------------------------------------+
//| Freeze-level check before PositionModify                            |
//+------------------------------------------------------------------+
bool FreezeOK(const ENUM_ORDER_TYPE type, const double open_price,
              const double sl, const double tp)
  {
   const int freeze_level = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_FREEZE_LEVEL);
   if(freeze_level <= 0)
      return(true);
   const double dist = freeze_level * _Point;
   const double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   const double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   if(type == ORDER_TYPE_BUY)
     {
      if(sl > 0.0 && bid - sl < dist)
         return(false);
      if(tp > 0.0 && tp - bid < dist)
         return(false);
     }
   else
     {
      if(sl > 0.0 && sl - ask < dist)
         return(false);
      if(tp > 0.0 && ask - tp < dist)
         return(false);
     }
   return(true);
  }

//+------------------------------------------------------------------+
//| Retcode helpers                                                   |
//+------------------------------------------------------------------+
bool RetcodeOK(const uint retcode)
  {
   return(retcode == TRADE_RETCODE_DONE ||
          retcode == TRADE_RETCODE_DONE_PARTIAL ||
          retcode == TRADE_RETCODE_PLACED);
  }

bool RetcodeTransient(const uint retcode)
  {
   return(retcode == TRADE_RETCODE_REQUOTE ||
          retcode == TRADE_RETCODE_REJECT ||
          retcode == TRADE_RETCODE_TIMEOUT ||
          retcode == TRADE_RETCODE_PRICE_CHANGED ||
          retcode == TRADE_RETCODE_PRICE_OFF ||
          retcode == TRADE_RETCODE_CONNECTION);
  }

//+------------------------------------------------------------------+
//| Pre-flight checks before any order                                |
//+------------------------------------------------------------------+
bool OrderPreflight(const ENUM_ORDER_TYPE type, double &lots,
                    double &sl, double &tp)
  {
   if(!TradingAllowed())
      return(false);
   if(!MarketOpen() || !SpreadOK())
      return(false);
   lots = NormalizeLots(lots);
   if(lots <= 0.0)
      return(false);
   string vol_desc = "";
   if(!CheckVolumeValue(lots, vol_desc))
      return(false);
   if(TotalOurLots() + lots > InpMaxOpenLots)
      return(false);
   if(!CheckMoneyForTrade(_Symbol, lots, type))
      return(false);
   AdjustStops(type, sl, tp);
   return(true);
  }

//+------------------------------------------------------------------+
//| Market order with bounded retry + Sleep backoff (never busy-wait) |
//+------------------------------------------------------------------+
bool SendMarketOrder(const ENUM_ORDER_TYPE type, const double lots,
                     const double sl, const double tp, const string comment)
  {
   double adj_lots = lots;
   double adj_sl = sl;
   double adj_tp = tp;
   if(!OrderPreflight(type, adj_lots, adj_sl, adj_tp))
      return(false);
   for(int attempt = 1; attempt <= InpMaxRetries; attempt++)
     {
      bool sent = false;
      if(type == ORDER_TYPE_BUY)
         sent = g_trade.Buy(adj_lots, _Symbol, 0.0, adj_sl, adj_tp, comment);
      else
         sent = g_trade.Sell(adj_lots, _Symbol, 0.0, adj_sl, adj_tp, comment);
      const uint retcode = g_trade.ResultRetcode();
      if(sent && RetcodeOK(retcode))
        {
         g_any_trade = true;
         return(true);
        }
      if(!RetcodeTransient(retcode))
         break;
      Sleep(InpRetryBaseMs * attempt);
     }
   return(false);
  }

//+------------------------------------------------------------------+
//| Close a position by ticket with bounded retry                     |
//+------------------------------------------------------------------+
bool SafeClosePosition(const ulong ticket, const double lots = 0.0)
  {
   for(int attempt = 1; attempt <= InpMaxRetries; attempt++)
     {
      bool ok = false;
      if(lots > 0.0)
         ok = g_trade.PositionClosePartial(ticket, lots);
      else
         ok = g_trade.PositionClose(ticket);
      const uint retcode = g_trade.ResultRetcode();
      if(ok && RetcodeOK(retcode))
         return(true);
      if(!RetcodeTransient(retcode))
         break;
      Sleep(InpRetryBaseMs * attempt);
     }
   return(false);
  }

//+------------------------------------------------------------------+
//| Basket helpers (positions owned by this EA on this symbol)        |
//+------------------------------------------------------------------+
bool IsOurPosition()
  {
   return(PositionGetString(POSITION_SYMBOL) == _Symbol &&
          PositionGetInteger(POSITION_MAGIC) == InpMagic);
  }

int CountOurPositions()
  {
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      const ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket) && IsOurPosition())
         count++;
     }
   return(count);
  }

double TotalOurLots()
  {
   double lots = 0.0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      const ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket) && IsOurPosition())
         lots += PositionGetDouble(POSITION_VOLUME);
     }
   return(lots);
  }

double BasketFloatingProfit()
  {
   double profit = 0.0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      const ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket) && IsOurPosition())
         profit += PositionGetDouble(POSITION_PROFIT) +
                   PositionGetDouble(POSITION_SWAP);
     }
   return(profit);
  }

void CloseAllOurPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      const ulong ticket = PositionGetTicket(i);
      if(ticket > 0 && PositionSelectByTicket(ticket) && IsOurPosition())
         SafeClosePosition(ticket);
     }
  }

//+------------------------------------------------------------------+
//| Tester fallback: guarantee at least one trading operation          |
//+------------------------------------------------------------------+
void TesterFallbackTrade()
  {
   if(!MQLInfoInteger(MQL_TESTER) || g_any_trade || CountOurPositions() > 0)
      return;
   if(g_bars_seen < __MIN_BARS__ * 2)
      return;
   double lots = NormalizeLots(SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN));
   if(lots <= 0.0)
      lots = NormalizeLots(InpLots);
   const double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   const double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   if(bid <= 0.0 || ask <= 0.0)
      return;
   const int stops = (int)SymbolInfoInteger(_Symbol, SYMBOL_TRADE_STOPS_LEVEL);
   const double dist = MathMax(stops + 5, 50) * _Point;
   double sl = NormalizeDouble(bid - dist, _Digits);
   double tp = NormalizeDouble(bid + dist, _Digits);
   SendMarketOrder(ORDER_TYPE_BUY, lots, sl, tp, "EAF_VAL");
  }

//+------------------------------------------------------------------+
//| Chart dashboard (OBJ_LABEL)                                       |
//+------------------------------------------------------------------+
void DashboardLabel(const string name, const int y, const string text)
  {
   const string obj = "EAF_" + name;
   if(ObjectFind(0, obj) < 0)
     {
      ObjectCreate(0, obj, OBJ_LABEL, 0, 0, 0);
      ObjectSetInteger(0, obj, OBJPROP_CORNER, CORNER_LEFT_UPPER);
      ObjectSetInteger(0, obj, OBJPROP_XDISTANCE, 8);
      ObjectSetInteger(0, obj, OBJPROP_YDISTANCE, y);
      ObjectSetInteger(0, obj, OBJPROP_FONTSIZE, 9);
      ObjectSetInteger(0, obj, OBJPROP_COLOR, clrWhite);
      ObjectSetString(0, obj, OBJPROP_FONT, "Consolas");
     }
   ObjectSetString(0, obj, OBJPROP_TEXT, text);
  }

void DashboardCreate()
  {
   DashboardLabel("title", 16, "__EA_NAME__  [magic " +
                  IntegerToString((int)InpMagic) + "]");
  }

void DashboardUpdate()
  {
   if(!InpShowDashboard)
      return;
   const double equity  = AccountInfoDouble(ACCOUNT_EQUITY);
   const double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   const double margin  = AccountInfoDouble(ACCOUNT_MARGIN);
   const double dd_pct  = 100.0 * SafeDiv(MathMax(balance - equity, 0.0), balance);
   const double spread  = (double)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   DashboardLabel("equity", 32, StringFormat("Equity : %.2f", equity));
   DashboardLabel("margin", 48, StringFormat("Margin : %.2f", margin));
   DashboardLabel("dd",     64, StringFormat("Live DD: %.2f %%", dd_pct));
   DashboardLabel("spread", 80, StringFormat("Spread : %.0f pts", spread));
   DashboardLabel("pos",    96, StringFormat("Basket : %d pos / %.2f lots",
                  CountOurPositions(), TotalOurLots()));
  }

//+------------------------------------------------------------------+
//| Signal evaluation: AND of every entry filter                      |
//+------------------------------------------------------------------+
bool SignalLong()
  {
   bool ok = true;
__SIGNAL_LONG__
   return(ok);
  }

bool SignalShort()
  {
   bool ok = true;
__SIGNAL_SHORT__
   return(ok);
  }

__FILTER_FUNCTIONS__

__MECHANIC_FUNCTIONS__

//+------------------------------------------------------------------+
//| Trade management: exit / risk overlay                             |
//+------------------------------------------------------------------+
// ATR value (price units) at the last closed bar; 0 when unavailable.
double TM_ATR()
  {
   if(g_tm_atr_handle == INVALID_HANDLE)
      return(0.0);
   double buf[];
   if(!SafeCopyBuffer(g_tm_atr_handle, 0, 1, 1, buf))
      return(0.0);
   return(buf[0]);
  }

// Initial protective-stop distance (points) for a fresh entry.
double TM_InitialStopPoints(const double base_sl_points)
  {
   if(Inp_X_sl_mode == 0)
      return(0.0);
   if(Inp_X_sl_mode == 2)
     {
      const double atr = TM_ATR();
      if(atr > 0.0)
         return(SafeDiv(atr, _Point) * Inp_X_atr_sl_mult);
     }
   return(base_sl_points);
  }

// Take-profit distance (points) given the chosen stop distance.
double TM_TakeProfitPoints(const double sl_points, const double base_tp_points)
  {
   if(Inp_X_tp_mode == 0)
      return(0.0);
   if(Inp_X_tp_mode == 2 && sl_points > 0.0)
      return(sl_points * Inp_X_tp_rr);
   return(base_tp_points);
  }

// Account-currency value of one point for one lot.
double TM_PointValue()
  {
   const double tick_value = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   const double tick_size  = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tick_size > 0.0)
      return(tick_value * (_Point / tick_size));
   return(tick_value);
  }

// Lot size for an entry: fixed, or risk-% sized off the stop distance.
double TM_Lots(const double sl_points)
  {
   if(Inp_X_lot_mode == 1 && sl_points > 0.0)
     {
      const double value_per_point = TM_PointValue();
      const double equity = AccountInfoDouble(ACCOUNT_EQUITY);
      const double risk_money = equity * Inp_X_risk_percent / 100.0;
      const double denom = sl_points * value_per_point;
      if(denom > 0.0)
         return(NormalizeLots(SafeDiv(risk_money, denom)));
     }
   return(NormalizeLots(InpLots));
  }

// Reset per-day counters at the start of each new trading day.
void TM_NewDayCheck()
  {
   MqlDateTime st;
   TimeToStruct(TimeCurrent(), st);
   if(st.day_of_year != g_tm_day)
     {
      g_tm_day = st.day_of_year;
      g_tm_trades_today = 0;
      g_tm_day_start_balance = AccountInfoDouble(ACCOUNT_BALANCE);
     }
  }

// Detect a just-closed losing trade and arm the cooldown timer.
void TM_TrackClosures()
  {
   const int pos = CountOurPositions();
   const double bal = AccountInfoDouble(ACCOUNT_BALANCE);
   if(Inp_X_cooldown_enabled == 1 && pos < g_tm_prev_positions
      && bal < g_tm_prev_balance)
      g_tm_cooldown_until = TimeCurrent() + (datetime)(Inp_X_cooldown_bars * PeriodSeconds());
   g_tm_prev_positions = pos;
   g_tm_prev_balance = bal;
  }

// Account-level entry gates.
bool TM_EntryAllowed()
  {
   if(Inp_X_time_filter == 1)
     {
      MqlDateTime st;
      TimeToStruct(TimeCurrent(), st);
      const int h = st.hour;
      const bool inside = (Inp_X_start_hour <= Inp_X_end_hour)
         ? (h >= Inp_X_start_hour && h < Inp_X_end_hour)
         : (h >= Inp_X_start_hour || h < Inp_X_end_hour);
      if(!inside)
         return(false);
     }
   if(Inp_X_limit_trades_per_day == 1 && g_tm_trades_today >= Inp_X_max_trades_per_day)
      return(false);
   if(Inp_X_daily_loss_enabled == 1 && g_tm_day_start_balance > 0.0)
     {
      const double eq = AccountInfoDouble(ACCOUNT_EQUITY);
      const double dd = (g_tm_day_start_balance - eq) / g_tm_day_start_balance * 100.0;
      if(dd >= Inp_X_daily_loss_pct)
         return(false);
     }
   if(Inp_X_cooldown_enabled == 1 && TimeCurrent() < g_tm_cooldown_until)
      return(false);
   return(true);
  }

// Trailing stop + breakeven applied to our directional positions.
void TM_ManageTrailing()
  {
   if(Inp_X_trail_mode == 0 && Inp_X_breakeven == 0)
      return;
   const double atr = TM_ATR();
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      const ulong ticket = PositionGetTicket(i);
      if(ticket == 0 || !PositionSelectByTicket(ticket) || !IsOurPosition())
         continue;
      const int d = (PositionGetInteger(POSITION_TYPE) == POSITION_TYPE_BUY) ? 1 : -1;
      const double entry  = PositionGetDouble(POSITION_PRICE_OPEN);
      const double cur_sl = PositionGetDouble(POSITION_SL);
      const double cur_tp = PositionGetDouble(POSITION_TP);
      const double price  = (d > 0) ? SymbolInfoDouble(_Symbol, SYMBOL_BID)
                                    : SymbolInfoDouble(_Symbol, SYMBOL_ASK);
      const double gain_points = SafeDiv(d * (price - entry), _Point);
      double new_sl = cur_sl;

      if(Inp_X_breakeven == 1 && gain_points >= Inp_X_be_trigger_points)
        {
         const double be = entry + d * Inp_X_be_offset_points * _Point;
         if(cur_sl == 0.0 || (d > 0 && be > cur_sl) || (d < 0 && be < cur_sl))
            new_sl = be;
        }

      if(Inp_X_trail_mode > 0 && gain_points >= Inp_X_trail_start_points)
        {
         double t_sl = 0.0;
         if(Inp_X_trail_mode == 1)
            t_sl = price - d * Inp_X_trail_distance_points * _Point;
         else if(Inp_X_trail_mode == 2 && atr > 0.0)
            t_sl = price - d * atr * Inp_X_trail_atr_mult;
         else if(Inp_X_trail_mode == 3 && atr > 0.0)
           {
            double ext[];
            const int lb = Inp_X_chandelier_lookback;
            if(d > 0 && SafeCopyHigh(1, lb, ext))
               t_sl = ext[ArrayMaximum(ext)] - atr * Inp_X_trail_atr_mult;
            else if(d < 0 && SafeCopyLow(1, lb, ext))
               t_sl = ext[ArrayMinimum(ext)] + atr * Inp_X_trail_atr_mult;
           }
         if(t_sl > 0.0)
           {
            const double step = Inp_X_trail_step_points * _Point;
            if(d > 0 && t_sl < price && (new_sl == 0.0 || t_sl > new_sl + step))
               new_sl = t_sl;
            else if(d < 0 && t_sl > price && (new_sl == 0.0 || t_sl < new_sl - step))
               new_sl = t_sl;
           }
        }

      if(new_sl > 0.0 && MathAbs(new_sl - cur_sl) > _Point / 2.0)
        {
         const double sl = NormalizeDouble(new_sl, _Digits);
         const ENUM_ORDER_TYPE otype = (d > 0) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
         if(FreezeOK(otype, entry, sl, cur_tp))
            g_trade.PositionModify(ticket, sl, cur_tp);
        }
     }
  }

//+------------------------------------------------------------------+
//| Main tick handler                                                 |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!HistoryReady(__MIN_BARS__))
      return;

   g_bars_seen++;
   DashboardUpdate();

   const datetime bar_time = iTime(_Symbol, _Period, 0);
   const bool new_bar = (bar_time != g_last_bar_time);
   if(new_bar)
      g_last_bar_time = bar_time;

   TM_NewDayCheck();
   TM_TrackClosures();
   ManagePositions();
   TM_ManageTrailing();

   if(!new_bar)
      return;
   if(!TradingAllowed() || !MarketOpen() || !SpreadOK())
      return;

   if(CountOurPositions() == 0 && TM_EntryAllowed())
     {
      if(SignalLong())
         OpenEntry(ORDER_TYPE_BUY);
      else if(SignalShort())
         OpenEntry(ORDER_TYPE_SELL);
     }

   TesterFallbackTrade();
  }
//+------------------------------------------------------------------+
