"""Native MT5 .set file export.

Every strategy parameter — entry filters AND execution mechanics (grid step,
hedge distance, lot multiplier, partial-close levels, ...) — is written in the
optimizable ``Value||Start||Step||Stop||Y`` format so the file can drive an
MT5 Strategy Tester optimization directly. Fixed general inputs are emitted
with the optimization flag off.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional

from factory.models import ParamRange, StrategyDefinition
from factory.mql5.renderer import mql5_inputs_for


def _fmt(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else f"{value:g}"


def build_set_content(strategy: StrategyDefinition,
                      params_override: Optional[Dict[str, float]] = None) -> str:
    if params_override:
        strategy = strategy.apply_flat_params(params_override)
    inputs, ranges = mql5_inputs_for(strategy)

    lines = [
        f"; {strategy.name} — generated by MQL5 EA Factory",
        f"; strategy id: {strategy.id}",
        "InpMagic=" + str(strategy.magic_number),
        "InpLots=" + _fmt(strategy.risk.fixed_lots),
        "InpMaxSpreadPoints=" + _fmt(strategy.risk.max_spread_points),
        "InpMaxOpenLots=" + _fmt(strategy.risk.max_open_lots),
    ]
    for name in sorted(inputs):
        value = _fmt(inputs[name])
        r: Optional[ParamRange] = ranges.get(name)
        if r is not None:
            lines.append(
                f"{name}={value}||{_fmt(r.min)}||{_fmt(r.step)}||{_fmt(r.max)}||Y")
        else:
            lines.append(f"{name}={value}||{value}||0||{value}||N")
    return "\n".join(lines) + "\n"


def write_set_file(strategy: StrategyDefinition, out_dir: Path,
                   params_override: Optional[Dict[str, float]] = None) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{strategy.name.replace(' ', '_')}.set"
    # MT5 reads .set files as UTF-16 LE with BOM
    path.write_text(build_set_content(strategy, params_override), encoding="utf-16")
    return path
